/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/uploads_files_3235541_Raspberry+pi+pico.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={[2.49, 0.94, 1.02]}>
        <mesh geometry={nodes.Plane_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane_2.geometry} material={materials.Front} />
        <mesh geometry={nodes.Plane_3.geometry} material={materials.Back} />
      </group>
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.003']} position={[2.03, 0.06, -0.57]} scale={0.01} />
      <mesh geometry={nodes.Text.geometry} material={materials['Material.005']} position={[0.89, 0.08, 0.43]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.06} />
      <mesh geometry={nodes.ic001.geometry} material={materials['Plastick IC']} position={[0.7, 0.06, 0.63]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.42, 0.24, 0.42]} />
      <mesh geometry={nodes.shield1002.geometry} material={materials['metal pin']} position={[2.29, 0.29, 0]} scale={[2.54, 2.54, 2.66]} />
      <mesh geometry={nodes.socket_housing1002.geometry} material={materials.blacky} position={[2.24, 0.05, 0]} scale={[2.54, 2.54, 2.66]} />
      <mesh geometry={nodes.socket_plate1002.geometry} material={materials['metal pin']} position={[2.24, 0.05, 0]} scale={[2.54, 2.54, 2.66]} />
      <mesh geometry={nodes.terminal1001.geometry} material={materials.gold} position={[2.32, 0.03, -0.14]} scale={[2.54, 2.54, 2.66]} />
      <mesh geometry={nodes.Text012.geometry} material={materials.IC_TEXT_COLOR} position={[0.7, 0.07, 0.62]} rotation={[0, Math.PI / 2, 0]} scale={[0.69, 0.5, 0.5]} />
      <mesh geometry={nodes.transister_pin038.geometry} material={materials['metal pin']} position={[0.63, 0.06, 0.58]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.5, 0.42, 0.42]} />
      <mesh geometry={nodes.transister_pin039.geometry} material={materials['metal pin']} position={[0.77, 0.06, 0.63]} scale={[0.52, 0.42, 0.42]} />
      <mesh geometry={nodes.transister_pin040.geometry} material={materials.gold} position={[2.05, 0.08, 0.13]} rotation={[0, Math.PI / 2, 0]} scale={[0.87, 1.26, 0.83]} />
      <group position={[1.19, 0.08, 0.29]} scale={[2, 1.83, 1.68]}>
        <mesh geometry={nodes.Cube083.geometry} material={materials.Y_body} />
        <mesh geometry={nodes.Cube083_1.geometry} material={materials['metal pin']} />
      </group>
      <group position={[-0.7, 0.07, -0.1]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.94, 0.86, 0.79]}>
        <mesh geometry={nodes.Cube084.geometry} material={materials['Y_body.003']} />
        <mesh geometry={nodes.Cube084_1.geometry} material={materials['metal pin']} />
      </group>
      <mesh geometry={nodes.transister_pin041.geometry} material={materials['metal pin']} position={[-0.41, 0.06, -0.26]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.32, 0.15, 0.47]} />
      <mesh geometry={nodes.Cylinder008.geometry} material={materials['Material.002']} position={[-2.38, 0.03, 0.89]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.1, 0.03, 0.13]} />
      <group position={[-0.05, 0.07, 0]} scale={[0.34, 0.02, 0.35]}>
        <mesh geometry={nodes.Cube086.geometry} material={materials['R_plastic.002']} />
        <mesh geometry={nodes.Cube086_1.geometry} material={materials.Label} />
      </group>
      <mesh geometry={nodes.Cylinder009.geometry} material={materials['Material.002']} position={[2.37, 0.03, -0.9]} scale={[0.1, 0.03, 0.13]} />
      <mesh geometry={nodes.Cylinder010.geometry} material={materials['Material.002']} position={[-2.37, 0.03, -0.24]} rotation={[0, Math.PI / 2, 0]} scale={[0.1, 0.03, 0.13]} />
      <group position={[1.68, 0.08, 0.29]} scale={[2, 1.83, 1.68]}>
        <mesh geometry={nodes.Cube001_1.geometry} material={materials.Y_body} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials['metal pin']} />
      </group>
      <group position={[0.45, 0.06, 0.45]} rotation={[0, Math.PI / 2, 0]} scale={[0.9, 0.83, 0.76]}>
        <mesh geometry={nodes.Cube002_1.geometry} material={materials.Y_body} />
        <mesh geometry={nodes.Cube002_2.geometry} material={materials['metal pin']} />
      </group>
      <group position={[0.45, 0.06, 0.31]} rotation={[0, Math.PI / 2, 0]} scale={[0.9, 0.83, 0.76]}>
        <mesh geometry={nodes.Cube003_1.geometry} material={materials.Y_body} />
        <mesh geometry={nodes.Cube003_2.geometry} material={materials['metal pin']} />
      </group>
      <group position={[0.45, 0.06, 0.22]} rotation={[0, Math.PI / 2, 0]} scale={[0.9, 0.83, 0.76]}>
        <mesh geometry={nodes.Cube004_1.geometry} material={materials.Y_body} />
        <mesh geometry={nodes.Cube004_2.geometry} material={materials['metal pin']} />
      </group>
      <group position={[0.45, 0.06, 0]} rotation={[0, Math.PI / 2, 0]} scale={[0.5, 0.45, 0.42]}>
        <mesh geometry={nodes.Cube005_1.geometry} material={materials.Y_body} />
        <mesh geometry={nodes.Cube005_2.geometry} material={materials['metal pin']} />
      </group>
      <group position={[0.45, 0.06, -0.07]} rotation={[0, Math.PI / 2, 0]} scale={[0.5, 0.45, 0.42]}>
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.Y_body} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['metal pin']} />
      </group>
      <group position={[0.87, 0.06, -0.45]} rotation={[0, Math.PI / 2, 0]} scale={[0.5, 0.45, 0.42]}>
        <mesh geometry={nodes.Cube007_1.geometry} material={materials.Y_body} />
        <mesh geometry={nodes.Cube007_2.geometry} material={materials['metal pin']} />
      </group>
      <group position={[0.22, 0.06, -0.45]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.5, 0.45, 0.42]}>
        <mesh geometry={nodes.Cube008.geometry} material={materials.Y_body} />
        <mesh geometry={nodes.Cube008_1.geometry} material={materials['metal pin']} />
      </group>
      <group position={[-0.15, 0.06, -0.45]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.5, 0.45, 0.42]}>
        <mesh geometry={nodes.Cube009.geometry} material={materials.Y_body} />
        <mesh geometry={nodes.Cube009_1.geometry} material={materials['metal pin']} />
      </group>
      <group position={[-0.54, 0.06, 0]} rotation={[0, -Math.PI / 2, 0]} scale={[0.5, 0.45, 0.42]}>
        <mesh geometry={nodes.Cube010.geometry} material={materials.Y_body} />
        <mesh geometry={nodes.Cube010_1.geometry} material={materials['metal pin']} />
      </group>
      <group position={[-0.54, 0.06, 0.07]} rotation={[0, -Math.PI / 2, 0]} scale={[0.5, 0.45, 0.42]}>
        <mesh geometry={nodes.Cube011.geometry} material={materials.Y_body} />
        <mesh geometry={nodes.Cube011_1.geometry} material={materials['metal pin']} />
      </group>
      <group position={[0.24, 0.06, 0.45]} scale={[0.5, 0.45, 0.42]}>
        <mesh geometry={nodes.Cube012.geometry} material={materials.Y_body} />
        <mesh geometry={nodes.Cube012_1.geometry} material={materials['metal pin']} />
      </group>
      <group position={[0.93, 0.06, 0.59]} rotation={[0, 1.57, 0]} scale={[0.5, 0.45, 0.42]}>
        <mesh geometry={nodes.Cube013.geometry} material={materials.Y_body} />
        <mesh geometry={nodes.Cube013_1.geometry} material={materials['metal pin']} />
      </group>
      <group position={[-0.19, 0.06, 0.45]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={[0.5, 0.45, 0.42]}>
        <mesh geometry={nodes.Cube014.geometry} material={materials.Y_body} />
        <mesh geometry={nodes.Cube014_1.geometry} material={materials['metal pin']} />
      </group>
      <group position={[0.3, 0.06, -0.46]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.9, 0.83, 0.76]}>
        <mesh geometry={nodes.Cube015.geometry} material={materials.Y_body} />
        <mesh geometry={nodes.Cube015_1.geometry} material={materials['metal pin']} />
      </group>
      <mesh geometry={nodes.transister_pin001.geometry} material={materials['metal pin']} position={[0.3, 0.06, 0.26]} scale={[-0.32, 0.15, 0.47]} />
      <mesh geometry={nodes.transister_pin002.geometry} material={materials['metal pin']} position={[0.2, 0.06, -0.36]} rotation={[0, 1.57, 0]} scale={[-0.32, 0.15, 0.47]} />
      <mesh geometry={nodes.transister_pin003.geometry} material={materials['metal pin']} position={[-0.3, 0.06, 0.36]} rotation={[0, -Math.PI / 2, 0]} scale={[-0.32, 0.15, 0.47]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['R_plastic.002']} position={[0.63, 0.07, -0.38]} scale={[0.15, 0.02, 0.1]} />
      <mesh geometry={nodes.transister_pin004.geometry} material={materials['metal pin']} position={[0.46, 0.06, -0.45]} rotation={[Math.PI, 0, Math.PI]} scale={[-0.32, 0.15, 0.6]} />
      <mesh geometry={nodes.transister_pin005.geometry} material={materials['metal pin']} position={[0.79, 0.06, -0.3]} scale={[-0.32, 0.15, 0.6]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['R_plastic.002']} position={[1.44, 0.07, 0.28]} scale={[0.12, 0.02, 0.12]} />
      <mesh geometry={nodes.transister_pin006.geometry} material={materials['metal pin']} position={[1.53, 0.06, 0.15]} rotation={[0, Math.PI / 2, 0]} scale={[-0.32, 0.15, 0.6]} />
      <mesh geometry={nodes.transister_pin007.geometry} material={materials['metal pin']} position={[1.34, 0.06, 0.41]} rotation={[0, -1.57, 0]} scale={[-0.32, 0.15, 0.6]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['R_plastic.002']} position={[1.44, 0.07, 0.59]} scale={[0.13, 0.02, 0.12]} />
      <group position={[-0.09, 0.07, 0.6]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.94, 0.86, 0.83]}>
        <mesh geometry={nodes.Cube026.geometry} material={materials['Y_body.003']} />
        <mesh geometry={nodes.Cube026_1.geometry} material={materials['metal pin']} />
      </group>
      <group position={[0, 0.07, 0.6]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.94, 0.86, 0.83]}>
        <mesh geometry={nodes.Cube027.geometry} material={materials['Y_body.003']} />
        <mesh geometry={nodes.Cube027_1.geometry} material={materials['metal pin']} />
      </group>
      <group position={[0.45, 0.07, 0.63]} rotation={[0, -Math.PI / 2, 0]} scale={[0.94, 0.86, 0.83]}>
        <mesh geometry={nodes.Cube028.geometry} material={materials['Y_body.003']} />
        <mesh geometry={nodes.Cube028_1.geometry} material={materials['metal pin']} />
      </group>
      <group position={[0.45, 0.07, 0.54]} rotation={[0, -Math.PI / 2, 0]} scale={[0.94, 0.86, 0.83]}>
        <mesh geometry={nodes.Cube029.geometry} material={materials['Y_body.003']} />
        <mesh geometry={nodes.Cube029_1.geometry} material={materials['metal pin']} />
      </group>
      <group position={[0.94, 0.07, 0.68]} rotation={[0, -Math.PI / 2, 0]} scale={[0.94, 0.86, 0.83]}>
        <mesh geometry={nodes.Cube030.geometry} material={materials['Y_body.003']} />
        <mesh geometry={nodes.Cube030_1.geometry} material={materials['metal pin']} />
      </group>
      <group position={[0.45, 0.06, 0.13]} rotation={[0, -Math.PI / 2, 0]} scale={[0.54, 0.49, 0.47]}>
        <mesh geometry={nodes.Cube031.geometry} material={materials['Y_body.003']} />
        <mesh geometry={nodes.Cube031_1.geometry} material={materials['metal pin']} />
      </group>
      <group position={[0.45, 0.06, 0.07]} rotation={[0, -Math.PI / 2, 0]} scale={[0.54, 0.49, 0.47]}>
        <mesh geometry={nodes.Cube032.geometry} material={materials['Y_body.003']} />
        <mesh geometry={nodes.Cube032_1.geometry} material={materials['metal pin']} />
      </group>
      <group position={[0.73, 0.07, -0.55]} rotation={[0, -Math.PI / 2, 0]} scale={[0.94, 0.86, 0.83]}>
        <mesh geometry={nodes.Cube033.geometry} material={materials['Y_body.003']} />
        <mesh geometry={nodes.Cube033_1.geometry} material={materials['metal pin']} />
      </group>
      <group position={[1.75, 0.07, -0.27]} scale={[0.94, 0.86, 0.83]}>
        <mesh geometry={nodes.Cube034.geometry} material={materials['Y_body.003']} />
        <mesh geometry={nodes.Cube034_1.geometry} material={materials['metal pin']} />
      </group>
      <group position={[1.85, 0.07, -0.27]} scale={[0.94, 0.86, 0.83]}>
        <mesh geometry={nodes.Cube035.geometry} material={materials['Y_body.003']} />
        <mesh geometry={nodes.Cube035_1.geometry} material={materials['metal pin']} />
      </group>
      <group position={[2.03, 0.08, -0.57]} scale={[1.63, 1.49, 1.37]}>
        <mesh geometry={nodes.Cube036.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Cube036_1.geometry} material={materials['metal pin']} />
      </group>
      <group position={[1.33, 0.07, -0.35]}>
        <mesh geometry={nodes.Cube038.geometry} material={materials.rough_metal} />
        <mesh geometry={nodes.Cube038_1.geometry} material={materials['Material.004']} />
      </group>
      <mesh geometry={nodes.transister_pin008.geometry} material={materials['metal pin']} position={[1.09, 0.07, -0.45]} rotation={[Math.PI, 0, Math.PI]} scale={[-0.76, 0.65, 2.05]} />
      <mesh geometry={nodes.transister_pin009.geometry} material={materials['metal pin']} position={[1.09, 0.07, -0.24]} rotation={[Math.PI, 0, Math.PI]} scale={[-0.76, 0.65, 2.05]} />
      <mesh geometry={nodes.transister_pin010.geometry} material={materials['metal pin']} position={[1.57, 0.07, -0.25]} scale={[-0.76, 0.65, 2.05]} />
      <mesh geometry={nodes.transister_pin011.geometry} material={materials['metal pin']} position={[1.57, 0.07, -0.46]} scale={[-0.76, 0.65, 2.05]} />
      <group position={[0.9, 0.07, 0.43]} rotation={[0, -Math.PI / 2, 0]} scale={[1.32, 1.3, 1.46]}>
        <mesh geometry={nodes.Cube043.geometry} material={materials['Y_body.003']} />
        <mesh geometry={nodes.Cube043_1.geometry} material={materials['metal pin']} />
      </group>
      <group position={[-0.85, 0.06, 0]} rotation={[0, -Math.PI / 2, 0]} scale={[0.54, 0.49, 0.41]}>
        <mesh geometry={nodes.Cube044.geometry} material={materials['Y_body.001']} />
        <mesh geometry={nodes.Cube044_1.geometry} material={materials['metal pin']} />
      </group>
      <group position={[-0.94, 0.06, -0.45]} rotation={[0, -Math.PI / 2, 0]} scale={[0.54, 0.49, 0.41]}>
        <mesh geometry={nodes.Cube045.geometry} material={materials['Y_body.001']} />
        <mesh geometry={nodes.Cube045_1.geometry} material={materials['metal pin']} />
      </group>
      <mesh geometry={nodes.Cube006.geometry} material={materials['Plastick IC.001']} position={[1.86, 0.1, 0.59]} scale={[0.5, 0.4, 0.51]} />
      <group position={[-0.89, 0.09, -0.22]} rotation={[Math.PI, 0, 0]} scale={[0.68, 0.5, 0.49]}>
        <mesh geometry={nodes.Cube057.geometry} material={materials.rough_metal} />
        <mesh geometry={nodes.Cube057_1.geometry} material={materials['gold.001']} />
      </group>
      <mesh geometry={nodes.Text001.geometry} material={materials['IC_TEXT_COLOR.001']} position={[1.84, 0.14, 0.58]} scale={[0.78, 0.24, 0.53]} />
      <mesh geometry={nodes.transister_pin013.geometry} material={materials.rough_metal} position={[1.73, 0.07, 0.58]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.03, 0.01, 0.06]} />
      <mesh geometry={nodes.transister_pin012.geometry} material={materials.rough_metal} position={[2, 0.07, 0.58]} scale={[0.03, 0.01, 0.06]} />
      <mesh geometry={nodes.Text002.geometry} material={materials['IC_TEXT_COLOR.001']} position={[-0.93, 0.13, -0.17]} rotation={[0, Math.PI / 2, 0]} scale={[0.74, 0.23, 0.51]} />
      <mesh geometry={nodes.Text003.geometry} material={materials['IC_TEXT_COLOR.001']} position={[-0.87, 0.13, -0.22]} rotation={[0, Math.PI / 2, 0]} scale={[0.74, 0.23, 0.51]} />
      <mesh geometry={nodes.transister_pin015.geometry} material={materials.rough_metal} position={[-0.82, 0.06, -0.06]} rotation={[0, -Math.PI / 2, 0]} scale={[0.01, 0.01, 0.04]} />
      <mesh geometry={nodes.transister_pin014.geometry} material={materials.rough_metal} position={[-0.97, 0.06, -0.06]} rotation={[0, -Math.PI / 2, 0]} scale={[0.01, 0.01, 0.04]} />
      <mesh geometry={nodes.transister_pin016.geometry} material={materials.rough_metal} position={[-0.97, 0.06, -0.38]} rotation={[0, 1.57, 0]} scale={[0.01, 0.01, 0.04]} />
      <mesh geometry={nodes.transister_pin017.geometry} material={materials.rough_metal} position={[-0.82, 0.06, -0.38]} rotation={[0, 1.57, 0]} scale={[0.01, 0.01, 0.04]} />
    </group>
  )
}

useGLTF.preload('/uploads_files_3235541_Raspberry+pi+pico.glb')
